### PR TITLE
Process text-to-image requested image count sequentially

### PR DESCRIPTION
**Pull request by ad-astra-video**
Updated the text-to-image to sequentially process images if more than 1 requested.

This provides more stable on GPU memory usage and I believe inference is relatively linear for text-to-image models.  If a user wants faster inference they can split the request to separate requests that would go to separate orchestrators.

This is a quick fix for issue [#49](https://github.com/livepeer/ai-worker/issues/49).

Some questions:
1) Should we set a sensible limit per request?  Timeout seems to be 30s so 15 sounds like a good limit that would allow most graphics cards to respond within the timeout.
2) Is there a check for if a set of images is requested but non-matching number of seeds is provided?  For example, batch of 10 requested but only 5 seeds provided.  I was not seeing where it would fill out the seeds to match the requested images count.

### CODE REVIEW

**Comment by ad-astra-video** [comment]
Did some testing and when I get past 12 images, the first ones processed return an ErrNotFound from the broadcaster.  15 images returns 3 ErrNotFound, 13 returns 1 ErrNotFound.  20 returns 8 ErrNotFound.

Is there a limit of 12 somewhere? or is this just my setup?

**Comment by ad-astra-video** [comment]
> Did some testing and when I get past 12 images, the first ones processed return an ErrNotFound from the broadcaster. 15 images returns 3 ErrNotFound, 13 returns 1 ErrNotFound. 20 returns 8 ErrNotFound.
> 
> Is there a limit of 12 somewhere? or is this just my setup?

I think I found it, the MemoryDriver in go-tools has a cache length of 12. Node uses a session based cache setup here https://github.com/livepeer/go-livepeer/blob/930533388e62d21b339cccd8d6f4348dc14c5e75/cmd/livepeer/starter/starter.go#L1170.  

Memory driver is in livepeer go-tools repo.  https://github.com/livepeer/go-tools/blob/ac33a3c30a694a743f0077630aaf62423b5fd1f9/drivers/local.go#L17

**Comment by eliteprox** [comment]
>     1. Should we set a sensible limit per request?  Timeout seems to be 30s so 15 sounds like a good limit that would allow most graphics cards to respond within the timeout.

I think we should set a reasonable limit for the number of files sent to a given orchestrator and send remainder to the next orchestrator in the pool if one is available.

>     2. Is there a check for if a set of images is requested but non-matching number of seeds is provided?  For example, batch of 10 requested but only 5 seeds provided.  I was not seeing where it would fill out the seeds to match the requested images count.

I'll have to debug/learn the multi-file workflow first, but this line should be generating a seed when it's not provided https://github.com/livepeer/ai-worker/pull/66/files#diff-2952f66b536acb78e9bb5ee0337a00485762b802438a3209508b3b0ee088212dR62

**Comment by ad-astra-video** [comment]
Updated to lastest `main` branch and force pushed to overwrite prior commits.

**Comment by ad-astra-video** [comment]
> > ```
> > 1. Should we set a sensible limit per request?  Timeout seems to be 30s so 15 sounds like a good limit that would allow most graphics cards to respond within the timeout.
> > ```
> 
> I think we should set a reasonable limit for the number of files sent to a given orchestrator and send remainder to the next orchestrator in the pool if one is available.
> 
> > ```
> > 2. Is there a check for if a set of images is requested but non-matching number of seeds is provided?  For example, batch of 10 requested but only 5 seeds provided.  I was not seeing where it would fill out the seeds to match the requested images count.
> > ```
> 
> I'll have to debug/learn the multi-file workflow first, but this line should be generating a seed when it's not provided https://github.com/livepeer/ai-worker/pull/66/files#diff-2952f66b536acb78e9bb5ee0337a00485762b802438a3209508b3b0ee088212dR62

@rickstaa added a generator to create enough seeds if the images requested > 1.  

My understanding of the os memory driver is it will fail to retrieve images from the gateway if greater than 12 are requested so we have a limit at 12 I believe but no error providing that it will fail after 12 is requested.

**Comment by eliteprox** [comment]
It sounds like we need to set a cap of 12 since that is the technical limit, but for reasonable processing time that might need to be even lower.

**Comment by rickstaa** [comment]
@ad-astra-video merged into the main branch. Thanks a lot 🚀!

**Comment by rickstaa** [comment]
> It sounds like we need to set a cap of 12 since that is the technical limit, but for reasonable processing time that might need to be even lower.

Let's deal with this in a subsequent pull request I created https://linear.app/livepeer-ai-spe/issue/LIV-380/throw-warning-when-user-requests-a-bathc-with-more-than-12-images to track this issue.

**Pull request merged**
