### PR TITLE
Add live_video_to_video pipeline

### PR DESCRIPTION
**Pull request by emranemran**
Base work for the Realtime Video AI Pipeline

### CODE REVIEW

**Comment by j0sh** [comment]
Is the pipeline 'video-to-video' ? I have been calling it 'live-video-to-video' - see https://github.com/livepeer/go-livepeer/pull/3210

Can the main branch be main? Easier to track and keep up to date, and it seems there is a lot of stuff in the `feature/live-ai` that we do not need

**Comment by j0sh** [comment]
Fixed docker paths in https://github.com/livepeer/ai-worker/pull/233/commits/b302de95022a14aa586a26c3586e283465185490 @emranemran - the commit showed up as you since it was from your machine

**Review by leszko — APPROVED** [review]
Good enough to merge into `main` and work from there. Also it does not touch any existing code, so nothing should break :)

**Comment by j0sh** [comment]
I like the flattening of `app/python/infer` into `app/infer`. Everything in this repo involves inference though... how about `app/live` since that describes the use case?

**Comment by leszko** [comment]
> I like the flattening of `app/python/infer` into `app/infer`. Everything in this repo involves inference though... how about `app/live` since that describes the use case?

I think it's a good idea. Let me rename it

**Pull request merged**
