### PR TITLE
add upscale image support to AI pipelines

### PR DESCRIPTION
**Pull request by mikezupper**
add support to upscale images using _timbrooks/instruct-pix2pix_ model

### CODE REVIEW

**Review by eliteprox — CHANGES_REQUESTED** [review]
These changes look good, tested successfully. There is just one change needed to add the default containerHostPort for the new upscale pipeline.

I opened a PR to your branch to add it, please review https://github.com/mikezupper/livepeer-ai-worker/pull/4

**Review by eliteprox — APPROVED** [review]
LGTM! Thanks for the PR @mikezupper

**Comment by rickstaa** [comment]
@mikezupper I made some small changes and updated the code with the latest version but apart from that this pull request seems good for a merge 👍🏻. Thanks!

**Comment by rickstaa** [comment]
@mikezupper, I noticed that this pull request did not work for me with go-livepeer. It seems you may have forgotten to add the route to the `gen_openapi.py` script or manually update the specs. I fixed this issue in [this commit](https://github.com/livepeer/ai-worker/pull/96/commits/73c23d8fd41aebedb8ffd6ce8c527b3f74960d42#diff-72d6aa5ce77520ae956845eb7e4e34862def18ebd52ca52c0f288b178a55c7db), and now it works correctly. 👍🏻

I'm very happy with the cleanliness of the implementation. This serves as an excellent example of a pull request for adding a new pipeline. 🎉

**Pull request merged**
