### PR TITLE
Add live-video-to-video pipeline schema

### PR DESCRIPTION
**Pull request by j0sh**
Calling this the 'live-video-to-video' pipeline for now

### CODE REVIEW

**Comment by j0sh** [comment]
this is quite the merge conflict 😵‍💫 

image

**Comment by rickstaa** [comment]
> this is quite the merge conflict 😵‍💫
> 
> image

Hey @j0sh happy to help 🤔. Those files are auto generated. Are your changes manual?

**Comment by rickstaa** [comment]
@j0sh these files are created based directly on the FastAPI running inside the container. Based on your usecase I can advise you on how to add your OpenAPI specifications to the generated OpenAPI spec. I added a warning so that developers are aware how the spec is generated https://github.com/livepeer/ai-worker/pull/238.

**Comment by j0sh** [comment]
Superseded by https://github.com/livepeer/ai-worker/pull/252

**Pull request closed without merging**
