### PR TITLE
Add LoRa support to the `txt2img` and `img2img` pipelines

### PR DESCRIPTION
**Pull request by stronk-dev**
Adds support to load in arbitrary embeddings, modules (like LCM), etc.

Fullfills https://github.com/livepeer/bounties/issues/33

Still requires:
~~- Testing if it works~~
~~- Gracefully deal with non-existing requested LoRas~~
~~Design decision: do we want to keep LoRas loaded, or always unload already loaded weights like we do now~~
~~Design decision: use the current method of requesting LoRas, or explore other options~~
~~Design decision: abort inference if one of the `loras` param is invalid or it fails to load one of the LoRas, or continue on like it does now~~

LoRas can be loaded by passing a new `loras` parameter. In the current design this needs to be a string, parseable as JSON. For example: `curl -X POST -H "Content-Type: application/json" localhost:8000/text-to-image -d '{"prompt":"light saber battle in the death star", "loras": "{ \"nerijs/pixel-art-xl\" : 1.2 }"}'`

### CODE REVIEW

**Comment by stronk-dev** [comment]
Did some testing:

```
2024-07-16 13:38:15,602 INFO:     Application startup complete.
2024-07-16 13:38:15,604 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
100%|██████████| 50/50 [00:06<00:00,  7.93it/s]
2024-07-16 13:38:23,625 INFO:     172.17.0.1:52384 - "POST /text-to-image HTTP/1.1" 200 OK
100%|██████████| 50/50 [00:08<00:00,  6.24it/s]
2024-07-16 13:39:10,578 INFO:     172.17.0.1:35758 - "POST /text-to-image HTTP/1.1" 200 OK
100%|██████████| 50/50 [00:06<00:00,  8.13it/s]
2024-07-16 13:39:22,707 INFO:     172.17.0.1:34084 - "POST /text-to-image HTTP/1.1" 200 OK
100%|██████████| 50/50 [00:08<00:00,  6.23it/s]
2024-07-16 13:39:36,599 INFO:     172.17.0.1:39376 - "POST /text-to-image HTTP/1.1" 200 OK
```

All images on a 4090, SDXL base model using prompt `light saber battle in the death star`. Requests 1 and 3 are without LoRas. Requests 2 and 4 requested the `nerijs/pixel-art-xl` LoRa. 

img1
img2
img3
img4

Interesting inference is a bit slower when using LoRas. I could've used a better trigger words in the prompt, but certainly seems like the LoRa was loaded.

One thing which we might want to rethink if the way to pass `loras` parameter:

`curl -X POST -H "Content-Type: application/json" localhost:8000/text-to-image -d '{"prompt":"light saber battle in the death star", "loras": "{ \"nerijs/pixel-art-xl\" : 1.2 }"}'`

**Comment by stronk-dev** [comment]
If the user requests an invalid LoRa repo, it will print the error `2024-07-16 14:14:03,062 - app.pipelines.util - WARNING - Unable to load LoRas for adapter 'nerijs/pixel-ar' (RepositoryNotFoundError)`

We can make this more verbose by printing the entire exeption. The runner will continue with inference, but without using the LoRa

**Comment by stronk-dev** [comment]
(as a sidenote: i think it would be useful if exceptions like that are collected and passed back. Make a best effort to complete inference and inform the user of any issues it found during the job. Alternatively we could also abort inference)

**Comment by eliteprox** [comment]
> If the user requests an invalid LoRa repo, it will print the error `2024-07-16 14:14:03,062 - app.pipelines.util - WARNING - Unable to load LoRas for adapter 'nerijs/pixel-ar' (RepositoryNotFoundError)`
> 
> We can make this more verbose by printing the entire exeption. The runner will continue with inference, but without using the LoRa

I like your LoRa input validation solution because it handles all incorrect values sufficiently. However, we might want to return these errors to the gateway later to inform the user. I think we should return the error from `load_loras` and return a bad request in the runner in case of an invalid lora or weight so go-livepeer can return it. I like the error messages you have now, I don't think more detail is needed on them.

We could also hold off on making that change until we develop the go-livepeer side, @rickstaa any thoughts on that approach?

**Comment by eliteprox** [comment]
> Design decision: do we want to keep LoRas loaded, or always unload already loaded weights like we do now
VRAM usage looks great, I tested with multiple concurrent requests of different loras. I think this is working good as it is. If this would enhance inference time, I think we should backlog it as a pipeline improvement.

> Design decision: use the current method of requesting LoRas, or explore other options
This implementation appears to be working great, I tried a few LoRas from hugging-face and they are downloaded automatically

**Review by eliteprox — CHANGES_REQUESTED** [review]
Thanks for the PR @stronk-dev! This a nice addition to the image pipelines. I tested both text-to-image and image-to-image using the `ByteDance/SDXL-Lightning` mdoel with two different loras and multiple images. The pipelines are working great with LoRa support.

See my comments above on the remaining design decisions. I think responding with an informative `bad request` response when invalid LoRa values are passed will help inform the user on the gateway side. If you can make that change (or we decide to do it during go-livepeer integration) and resolve conflicts then the PR looks good to me.

**Comment by rickstaa** [comment]
Intersting 🤔! Not sure what went on during the OpenAPI spec configuration -> https://github.com/livepeer/ai-worker/pull/119/commits/dcaa961fbd6d07d957159da93384881dff669716. Maybe my generation code is no longer sufficient. Will revert https://github.com/livepeer/ai-worker/pull/119/commits/dcaa961fbd6d07d957159da93384881dff669716 and check on monday.

**Comment by stronk-dev** [comment]
> See my comments above on the remaining design decisions. I think responding with an informative `bad request` response when invalid LoRa values are passed will help inform the user on the gateway side. If you can make that change (or we decide to do it during go-livepeer integration) and resolve conflicts then the PR looks good to me.

Just to confirm: we should return a `bad request` error and abort inference for any of the Exceptions in `load_loras` function?

**Review by eliteprox — APPROVED** [review]
This change is ready merge if there's no further optimizations. Please review @stronk-dev  and @stronk-dev if you could take a quick look

**Comment by eliteprox** [comment]
> > See my comments above on the remaining design decisions. I think responding with an informative `bad request` response when invalid LoRa values are passed will help inform the user on the gateway side. If you can make that change (or we decide to do it during go-livepeer integration) and resolve conflicts then the PR looks good to me.
> 
> Just to confirm: we should return a `bad request` error and abort inference for any of the Exceptions in `load_loras` function?

Correct, and to send that back to the gateway. I think this would help developers learn the API faster, but not required for this initial release of LoRa support in my opinion, open to suggestions

**Comment by stronk-dev** [comment]
Thanks for all the tweaks, @eliteprox ! LGTM

**Comment by eliteprox** [comment]
> Thanks for all the tweaks, @eliteprox ! LGTM

@rickstaa I've resolved conflicts on `runner.gen.go` and re-generated the openapi schema. This is ready for merge along with https://github.com/livepeer/go-livepeer/pull/3154

**Comment by eliteprox** [comment]
@stronk-dev Just an update on this PR. There is one remaining task to load the 2-step, 4-step or 8-step checkpoints differently when LoRas are used on non-sdxl models. See [https://huggingface.co/ByteDance/SDXL-Lightning#2-step-4-step-8-step-lora](https://huggingface.co/ByteDance/SDXL-Lightning#2-step-4-step-8-step-lora) 

This logic is in t2i and i2i:
https://github.com/livepeer/ai-worker/blob/feature/loras/runner/app/pipelines/text_to_image.py#L86
https://github.com/livepeer/ai-worker/blob/feature/loras/runner/app/pipelines/image_to_image.py#L76

**Comment by rickstaa** [comment]
> (as a sidenote: i think it would be useful if exceptions like that are collected and passed back. Make a best effort to complete inference and inform the user of any issues it found during the job. Alternatively we could also abort inference)

@stronk-dev I agree -> https://github.com/livepeer/ai-worker/pull/188.

**Comment by rickstaa** [comment]
> See my comments above on the remaining design decisions. I think responding with an informative `bad request` response when invalid LoRa values are passed will help inform the user on the gateway side. If you can make that change (or we decide to do it during go-livepeer integration) and resolve conflicts then the PR looks good to me.

@eliteprox good catch. Could you create a seperate linear item for it?

**Comment by rickstaa** [comment]
@stronk-dev thanks again for your contribution. To ensure optimal network performance and leaner code. I applied several improvements:

- I migrated the code into its own class.
- I added some logic to disable loras instead of unloading them when a request without loras comes through.
- I added loaded lora tracking so we only unload loras when needed.

# Output tests

I performed several output tests to ensure the loras were being applied and correctly disabled.

**Prompt**: `pixel, a cute corgi`.
**Negative prompt**: `3d render, realistic`.
**Base**: `stabilityai/stable-diffusion-xl-base-1.0`.
**Loras**: `{ \"latent-consistency/lcm-lora-sdxl\": 1.0, \"nerijs/pixel-art-xl\": 1.2}`.
**Guidance scale**: `1.5`.
**Inference steps** : `50`.

#### Without loras

```bash
{
  "model_id": "",
  "loras": "",
  "prompt": "pixel, a cute corgi",
  "height": 576,
  "width": 1024,
  "guidance_scale": 1.5,
  "negative_prompt": "3d render, realistic",
  "safety_check": true,
  "seed": 0,
  "num_inference_steps": 50,
  "num_images_per_prompt": 1
}
```

image

#### With loras

```
{
  "model_id": "",
  "loras": "{ \"latent-consistency/lcm-lora-sdxl\": 1.0, \"nerijs/pixel-art-xl\": 1.2}",
  "prompt": "pixel, a cute corgi",
  "height": 576,
  "width": 1024,
  "guidance_scale": 1.5,
  "negative_prompt": "3d render, realistic",
  "safety_check": true,
  "seed": 0,
  "num_inference_steps": 50,
  "num_images_per_prompt": 1
}
```

image

#### Next request wihout loras

image

#### Following request with loras again

image

#### Request without loras and negative prompt

image

#### Request with better parameters after lora was enabled

```bash
{
  "model_id": "",
  "loras": "",
  "prompt": "close-up photo of a beautiful red rose breaking through a cube made of ice , splintered cracked ice surface, frosted colors, blood dripping from rose, melting ice, Valentine’s Day vibes, cinematic, sharp focus, intricate, cinematic, dramatic light",
  "height": 576,
  "width": 1024,
  "guidance_scale": 7.5,
  "negative_prompt": "",
  "safety_check": true,
  "seed": 0,
  "num_inference_steps": 50,
  "num_images_per_prompt": 1
}
```

image

#### Request with better parameters on restart

```bash
{
  "model_id": "",
  "loras": "",
  "prompt": "close-up photo of a beautiful red rose breaking through a cube made of ice , splintered cracked ice surface, frosted colors, blood dripping from rose, melting ice, Valentine’s Day vibes, cinematic, sharp focus, intricate, cinematic, dramatic light",
  "height": 576,
  "width": 1024,
  "guidance_scale": 7.5,
  "negative_prompt": "",
  "safety_check": true,
  "seed": 0,
  "num_inference_steps": 50,
  "num_images_per_prompt": 1
}
```

image

**Comment by rickstaa** [comment]
@stronk-dev I will add one more optimization where we allow up to 4 loras but allow 8 loras in buffer and I will look at memory crashes. After that it is good to be merged.

**Comment by rickstaa** [comment]
@eliteprox and @stronk-dev I now also added some logic to cleanup memory when the free memory on the GPU goes below 2 GB.

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Another Check

#### Base

```bash
curl -X POST "http://0.0.0.0:8935/text-to-image" \
    -H "Content-Type: application/json" \
    -d '{
        "model_id":"stabilityai/stable-diffusion-xl-base-1.0",
        "loras": "{ \"latent-consistency/lcm-lora-sdxl\": 0.0, \"KappaNeuro/jim-mahfood-style\": 1.0}",
        "prompt":"A cool cat on the beach",
        "width": 1024,
        "height": 1024,
        "seed": 818566848
    }'
```



#### Loras

```bash
curl -X POST "http://0.0.0.0:8935/text-to-image" \
    -H "Content-Type: application/json" \
    -d '{
        "model_id":"stabilityai/stable-diffusion-xl-base-1.0",
        "loras": "{ \"alvdansen/dimension-w-sd15\": 1.0}",
        "prompt":"A cool cat on the beach",
        "width": 1024,
        "height": 1024,
        "seed": 818566848
    }'
```

35fe8924

#### Back to base

e212c406

**Review by eliteprox — APPROVED** [review]
Tested loading/unloading LoRa, max of 4 LoRas and validation of invalid LoRa values.

LGTM!

**Pull request merged**
